### ISSUE TITLE
`tkinter` widget support

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#136]
I think it would be really cool to allow people to use old tkinter widgets in `Tukaan` somehow so that their work doesn't have to be completely redone since both work on Tcl/Tk and if we add some tkinter methods just to make it compatible old programs could still work

**Comment by rdbende** [comment]
I am sceptical about this feature for a couple of reasons.

- The architecture of Tkinter and Tukaan is so different, it would be tricky to even emulate tkinter's API in Tukaan. The way it could work is creating a proxy root object, and patching tkinter's global root at runtime (when it is supported), or overwriting `w.tk`. This is risky, because it won't work for example, when a tkinter widget calls a Python method that is defined on tkinter widget, but not on tukaan widgets.
- Tukaan is conceptually different. It's not simply an interface to Tk, but a whole toolkit for creating desktop applications. This is why you don't start the program by creating a root window, but by initializing an app context.
Tkinter uses strings everywhere, because in Tcl everything is a string, and tkinter doesn't translate them back, so it's unpythonic most of the time, and quite annoying. The whole API is different, and I don't want people used to tkinter trying to use it the wrong way.
- It's not a good idea to mix GUI toolkits. Even though they both use Tcl/Tk under the hood, the API is really different. It would be really confusing, when certain common methods are defined on one widget, but not on another, or the name is the same, but they work differently. Binding strings are a bit different in tukaan, the grid geometry manager also behaves differently, and so even layouting and event management would be totally different between widgets.

That said, I think it's very important to make it easier to port tkinter apps to Tukaan, and I'd love to see people transition to Tukaan. However, instead of this feature I think it would be better to have a tool that helps to rewrite (or rewrites) an existing tkinter application to Tukaan. This would be a quite interesting and fun project imo.

**Comment by rdbende** [comment]
https://github.com/rdbende/tkupgrade

**Comment by Moosems** [comment]
I'll need to wait to convert DIP until the `Text` widget gets a widget in Tulane :(.
