### ISSUE TITLE
Integrate playsound module

### ISSUE THREAD

**Issue by not-nef** [tukaan/tukaan#49]

**Comment by insolor** [comment]
Why it is needed to be integrated into tukaan itself? Just run playsound in a separate thread.

**Comment by not-nef** [comment]
Well i just thought it would be useful

**Comment by insolor** [comment]
Maybe, if you specify what kind of integration do you mean, it would be clearer. From my perspective, it is easy to use playsound as is, as a separate package, without any additional integration.

As an example, what needs some kind of integration is [pystray][1], because there is no clear and obvious way how to add a tray icon when you use tkinter or tukaan. There is [some workaround on StackOverflow][2], but as far as I remember I had some problems with this approach on Linux.

[1]: https://github.com/moses-palmer/pystray
[2]: https://stackoverflow.com/a/54841035/4752653

**Comment by rdbende** [comment]
Well, I'm not going to integrate the `playsound` module, for several reasons.

1. `playsound` has only one function, which isn't a big deal to import from there instead of Tukaan
2. `playsound` advertises itself as no dependencies required, which is not true. On Linux you need the `PyGObject` package, which is a big dependency
3. `playsound` is dumb. It has only one function, which doesn't allow you to stop the music, edit it, or do anything useful with it. 
4. I'm currently implementing a **MUCH** better way to play, record, and edit sounds, so `playsound` is not necessary!
   <details><summary>Look at this!</summary>

   ```python
   # Play sound
   sound_to_play = tukaan.media.Sound("/home/rdbende/Music/OMD/Walking on the Milky Way.wav")
   sound_to_play.play()


   # Record sound
   sound_to_record = tukaan.media.Sound()

   with sound_to_record.record():
       tukaan.Timer.wait(10)

   sound_to_record.save("/home/rdbende/Music/recorded_with_tukaan.wav")


   # Edit sound
   # I don't wanna spoiler :D
   ```

   </details>

**Comment by rdbende** [comment]
@insolor I'm not sure in Pystray either.
It's a pain to get it working with Tkinter, since both have their own mainloops that block each other.

I might just implement the `tk systray` feature that's in Tk 8.7, although it would be nice to find a way to make Tukaan and Pystray work well together.

**Comment by sumeshir26** [comment]
But mac dosent have Tcl 8.7 unless you use annaconda, right?

**Comment by rdbende** [comment]
I won't add support for Tcl/Tk 8.7 until they release the stable version, so I don't think that's a problem.
