### ISSUE TITLE
Feature: Theme collection

### ISSUE THREAD

**Issue by sumeshir26** [tukaan/tukaan#74]

**Comment by rdbende** [comment]
I have quite a few other themes in development, and I'm planning to create a separate package to store Tukaan themes, similar to [ttkthemes](https://github.com/TkinterEP/ttkthemes)

**Comment by rdbende** [comment]
I'm also planning to include a nice default theme in Tukaan (either Sun Valley, or else).

**Comment by sumeshir26** [comment]
Thats awesome! Which themes are you making?

**Comment by rdbende** [comment]
I'm doing a vintage-90's design like this:
![image](https://user-images.githubusercontent.com/77941087/166121205-de986ad0-1e34-4df9-8650-3a1046f8099c.png)

And also a friendly, flat theme:
![image](https://user-images.githubusercontent.com/77941087/166121304-22e751cb-09ed-450a-a2d4-8691a8538703.png)
![image](https://user-images.githubusercontent.com/77941087/166121316-e82649bb-f8fe-44f2-b981-0a25dba439b5.png)

> Designs from Dribbble

**Comment by Moosems** [comment]
@rdbende I love the 90's style one!! It looks so pretty!

**Comment by blyamur** [comment]
What an interesting project would be if it were not for its political overtones...

**Comment by Moosems** [comment]
@blyamur What do you mean by `political overtones`?

**Comment by blyamur** [comment]
> political overtones
It is enough to open the project description page, and there is a badge, From a person who incites hatred between nations. Why this is in open source projects, I don’t understand ... Am I not right?

**Comment by insolor** [comment]
@blyamur 

The badge doesn't incite hatred, instead the actions of a group of people in the Kremlin and their army incite hatred.

Btw, there is a flag on your avatar, a flag of a country which fires missiles to another country, and you are complaining about political overtones? As they say, "either put on panties, or take off the cross"

**Comment by Moosems** [comment]
@blyamur Having a StandWithUkraine flag doesn't incite any violence. It shows that the owner and group stands with the people of Ukraine. Given the fact that Ukraine was innocent and is innocent in the Russo-Ukrainian war that means that it doesn't incite violence but rather shows that people are willing to stand up for innocent people

**Comment by rdbende** [comment]
@blyamur

A project is not made worse or better, more or less interesting, by what its authors think about the war and the world and how they communicate that.
I accept that you may disagree with what you see in the README, but I didn't put that badge there to incite hatred at all. If something is hateful, it is when someone's avatar contains the flag of a country that has been bombing a country and its innocent inhabitants for over two months. This project existed long before Russia invaded Ukraine, and I really hope that the war will be over sooner than this project.

I assume you have no personal experience with people fleeing from Putyin's war, otherwise you wouldn't wrote this. Well, I do.
As I meet them daily on the train, and have spoken to several of them when I volunteered, I know exactly that who I am standing up for. I don't claim to have acted with good judgment when I put this badge in the README, because I don't think there's much to think about whether I am publicly standing up for Ukraine and the refugees. Imo it's the least I **can** and **should** do for them.

If you want to have a political argument in the future, I don't mind, I'm willing to argue with you (although I think that Github isn't the right place to argue about politics), however, **please open a separate issue** (or better yet, a discussion) for it. Other people open these issues not to get into a political debate, but to report issues and discuss the project.

[#StandWithUkraine!](https://www.standwithukraine.how)

**Comment by blyamur** [comment]
> @blyamur
> 
> A project is not made worse or better, more or less interesting, by what its authors think about the war and the world and how they communicate that. I accept that you may disagree with what you see in the README, but I didn't put that badge there to incite hatred at all. If something is hateful, it is when someone's avatar contains the flag of a country that has been bombing a country and its innocent inhabitants for over two months. This project existed long before Russia invaded Ukraine, and I really hope that the war will be over sooner than this project.
> 
> I assume you have no personal experience with people fleeing from Putyin's war, otherwise you wouldn't wrote this. Well, I do. As I meet them daily on the train, and have spoken to several of them when I volunteered, I know exactly that who I am standing up for. I don't claim to have acted with good judgment when I put this badge in the README, because I don't think there's much to think about whether I am publicly standing up for Ukraine and the refugees. Imo it's the least I **can** and **should** do for them.
> 
> If you want to have a political argument in the future, I don't mind, I'm willing to argue with you (although I think that Github isn't the right place to argue about politics), however, **please open a separate issue** (or better yet, a discussion) for it. Other people open these issues not to get into a political debate, but to report issues and discuss the project.
> 
> [#StandWithUkraine!](https://www.standwithukraine.how)

And where were you all those 8 years while they were killing their fellow citizens? Donbass, Odessa... When were the children bombed? They killed my colleagues' relatives. Was it normal? 
It just so happens that the bad ones supply food and medicine and sacrifice themselves to save the civilian population, while the good ones pump up the country with weapons and encourage the killing of civilians. I have not seen Russian programmers calling for the murder of others, introducing backdoors and viruses into their code to harm residents of other time zones. I have not seen anyone raising funds for the continuation of the war. I have not seen calls to divide people into nations. But it is actively done by those whom you support. Your right. However, it is not necessary to tell me whether I can indicate the flag of my country on the avatar. At least I don't push it to everyone, I don't divide people by nationality. Good luck to you. One way or another, time will put everything in its place.

**Comment by insolor** [comment]
@blyamur

> And where were you all those 8 years while they were killing their fellow citizens? Donbass, Odessa... When were the children bombed? They killed my colleagues' relatives. Was it normal?

Russia caused the Donbass conflict, Ukraine just tried to take back their territory. Only Russia is responsible for these deaths.

And another question: where Russia were for those 8 years? For the last few years the conflict on Donbass were mostly frozen and there were just dozens of casualties a year, and now Russia escalates the conflict and now there are hundreds and thousands of killed Russian-speaking Ukrainians on Donbass, in Kharkiv, in Kyiv, in other places. And they call it "a defense of the people of Donbass"?

I have an answer for you: "a defense of the people of Donbass" is just a cover, the real cause of this war is just Putin's ambitions.

**Comment by rdbende** [comment]
@blyamur
I'm locking the conversation.
Please don't think I want to silence you, but this conversation is going nowhere and is neither relevant nor appropriate here.
