### ISSUE TITLE
Font support for Labels

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#79]
@rdbende  I'm unsure how to use fonts with Tukaan labels. How should I do this?

**Comment by rdbende** [comment]
I'm currently not able to implement it, but I think it's a good starting point for you.

It's basically just adding a `font` parameter to the `__init__`, and a key to `_keys`, and Tukaans' widget API does the rest for you.
You can see, how other parameters are implemented in `label.py`, and `textbox.py` specifically for font attributes.

**Comment by rdbende** [comment]
> tukaan.exceptions.TclError: unknown option "-font"

Nah, that is odd. I have to figure out why that happens, the manual page says that it works with Tk 8.5 and eith 8.6 as weel, so it shouldn't be an unknown option.

> "font": tuple,
...
font: tuple | None = None,
...
font=font,

In my opinion, managing fonts in Tkinter is kinda inconvenient. You have to create tuples with some random str values, and just in the right order, and if you want to skip a property from that order, you have to use Tcl-like kwargs, and whatnot. Again, since explicit is better than implicit, Tukaan has [a function](https://github.com/tukaan/tukaan/blob/master/tukaan/fonts.py#L467), that generates this tuple for you, so you can simply use keyword arguments, and it will return a Tcl-compatible tuple. Its full signature is this: `tuple[str | int | bool, ...]`.
The other thing that Tukaan has, is Font objects, that can be changed dinamically, so you can do
```python
some_widget.font.bold = True
```
and it will change every associated widgets' font to bold immediately. It's also possible to load a font from file woth them, so it gives you a lotta power.

As for `_keys` for the `TextBox` widget I defined the type as `Font` (the font object), but I forgot about the possibility to use the `font()` function. When using it, there's no `Font` object associated with the widget, so it can't really use that. Now I need to figure out, what should be that type, but you have to wait for that 😕.
```python
{"font": ????}
...
font: Font | tuple[str | int | bool, ...] | None = None,  # You'll have to 'from tukaan.fonts import Font' first
...
font=font

**Comment by Moosems** [comment]
- - - - Personally I really love the way that tkinter handles fonts for the user but I would like it if you didn't always have to give a size value. Tkinter is super flexible when it comes to fonts but I would also love it where it sturdy. I honestly really dislike making font objects and normally use 'normal_font=("Courier New bold", 15)'

**Comment by Moosems** [comment]
@rdbende Any updates?  I'm still hoping to fix this

**Comment by rdbende** [comment]
> @rdbende I added it as:
> 
> ```python
> "font": tuple,
> ...
> font: tuple | None = None,
> ...
> font=font,
> ```
> 
> But this gives the error:
> 
> ```
> File "/Users/Moosems/Desktop/tukaan/tukaan/widgets/button.py", line 44, in __init__
>     BaseWidget.__init__(
>   File "/Users/Moosems/Desktop/tukaan/tukaan/widgets/_base.py", line 316, in __init__
>     Tcl.call(None, self._tcl_class, self._name, *Tcl.to_tcl_args(**kwargs))
>   File "/Users/Moosems/Desktop/tukaan/tukaan/_tcl.py", line 174, in call
>     raise TclError(msg) from None
> tukaan.exceptions.TclError: unknown option "-font"
> ```

Ictually, I successfully implemented this today in the same way, so Idk what was the problem.

**Comment by Moosems** [comment]
Can you create a release for me to test it with?

**Comment by rdbende** [comment]
Soon!

**Comment by Moosems** [comment]
😀
